cmake_minimum_required(VERSION 3.29)
project(innobase_mini)

set(CMAKE_CXX_STANDARD 20)

add_executable(innobase_lite
        sql/mysqld.cc
        sql/sql_io/iterators/basic_row_iterators.cc
        sql/sql_io/iterators/basic_row_iterators.h
        sql/sql_io/iterators/row_iterator.h
        sql/sql_io/table.h
        sql/sql_exec/sql_tcl/b_handler.h
        sql/sql_exec/sql_tcl/b_handler.cc
        storage/innobase/a0_handler/ha_innodb.cc
        storage/innobase/a0_handler/ha_innodb.h
        storage/innobase/c_row/row0sel.cc
        storage/innobase/b0_trx/trx0trx.h
        storage/innobase/d0_btr/btr0pcur.h
        storage/innobase/d0_btr/btr0pcur.cc
        storage/innobase/d0_btr/btr0btr.h
        storage/innobase/e_buf/buf0buf.h
        storage/innobase/e_buf/buf0buf.cc
        storage/innobase/f_page/page0curr.cc
        storage/innobase/f_page/page0page.h
        storage/innobase/d0_btr/btr0btr.cc
        storage/innobase/f_page/page0types.h
        storage/innobase/c_row/row0mysql.h
        storage/innobase/f_page/page0cur.h
        storage/innobase/d2_mtr_later/mtr0mtr.h
        storage/innobase/d0_btr/btr0cur.cc
        storage/innobase/c_row/row0sel.h
        storage/innobase/b0_trx/trx0trx.cc
        storage/innobase/g_log_redo_wal/log0log.cc
        storage/innobase/d2_mtr_later/mtr0mtr.cc
        storage/innobase/e_buf/buf0rea.cc
        storage/innobase/h_fil_later/fil0fil.cc
        storage/innobase/e_buf/buf0flu.cc
        storage/innobase/b1_read_later/read0read.h
        storage/innobase/b0_trx/trx0sys.h
        storage/innobase/e_buf/buf0lru.cc
        storage/innobase/c_row/row0mysql.cc
        storage/innobase/c_row/row0ins.cc
        storage/innobase/b2_que_later/que0que.h
        storage/innobase/c_row/row0ins.h
        storage/innobase/c_row/data0data.h
        sql/sql_io/sql_base.cc
        sql/sql_io/sql_base.h
        storage/innobase/c_row/row0upd.h
        storage/innobase/b0_trx/trx0undo.cc
        storage/innobase/b0_trx/trx0undo.h
        storage/innobase/b3_fsp_later/fsp0fsp.cc
        storage/innobase/b3_fsp_later/fsp0fsp.h
        storage/innobase/a2_dict_later/dict.h
        storage/innobase/a2_dict_later/dict0mem.h
        sql/sql_exec/sql_tcl/c_tc_log.h
        sql/sql_exec/sql_tcl/c_tc_log.cc
        sql/sql_exec/sql_tcl/a0_transaction.h
        sql/sql_exec/sql_tcl/a0_transaction.cc
        sql/sql_exec/sql_tcl/a0_xa.h
        sql/sql_io/table.cc
        sql/sql_exec/sql_tcl/d_sql_plugin_ref.h
        sql/sql_exec/sql_tcl/d_sql_plugin_ref.cc
        sql/sql_exec/sql_tcl/z_transaction_info.cc
        sql/sql_exec/sql_tcl/z_transaction_info.h
        sql/my_alloc.h
        sql/sql_exec/sql_tcl/xa/sql_xa_commit.h
        sql/sql_exec/sql_tcl/xa/sql_xa_commit.cc
        sql/sql_exec/d1_sql_cmd.h
        storage/innobase/b4_rem_later/rec.cc
        storage/innobase/b4_rem_later/rec.h
        storage/innobase/b4_rem_later/rem0wrec.cc
        sql/sql_exec/b1_sql_parse.cc
        sql/sql_exec/b0_sql_lex.h
        sql/sql_exec/d0_mysql_sqlcommand.h
        sql/sql_exec/sql_dcl_later/sql_user.cc
        sql/sql_list.h
        sql/sql_exec/c1_sql_prepare.cc
        sql/sql_exec/sql_dml/a1_sql_cmd_dml.cc
        sql/sql_exec/sql_dml/b1_sql_insert.cc
        sql/sql_exec/sql_dql/a1_sql_select.cc
        sql/sql_io/sql_union.cc
        sql/sql_io/item.cc
        sql/sql_io/query_result.h
        sql/sql_io/field.cc
        sql/conn_handler/a_connection_acceptor.h
        sql/conn_handler/a_socket_connection.h
        sql/conn_handler/b1_connection_handler_manager.h
        sql/conn_handler/z_channel_info.h
        sql/conn_handler/b1_connection_handler_manager.cc
        sql/conn_handler/b0_connection_handler.h
        sql/conn_handler/c_connection_handler_impl.h
        sql/conn_handler/c_connection_handler_one_thread.cc
        sql/conn_handler/b0_connection_handler.cc
        sql/conn_handler/a_socket_connection.cc
        mysqld.cc
)
