#include "b0_sql_class.h"

/**
  Call parser to transform statement into a parse tree.
  Then, transform the parse tree further into an AST, ready for resolving.
*/
int my_sql_parser_parse(class THD * thd,class Parse_tree_root * *root) {
    // extern int my_sql_parser_parse(class THD * thd,class Parse_tree_root * *root);
    return 0;
}

bool THD::sql_parser() {
    /*
      SQL parser function generated by YACC from sql_yacc.yy.

      In the case of success returns 0, and THD::is_error() is false.
      Otherwise returns 1, or THD::>is_error() is true.

      The second (output) parameter "root" returns the new parse tree.
      It is undefined (unchanged) on error. If "root" is NULL on success,
      then the parser has already called lex->make_sql_cmd() internally.
    */
    // extern int my_sql_parser_parse(class THD * thd,class Parse_tree_root * *root);

    //1. SQL to Parse Tree
    Parse_tree_root *root = nullptr;
    if (my_sql_parser_parse(this, &root)) {
        return true;
    }

    //2. Parse Tree to AST
    if (root != nullptr && lex->make_sql_cmd(root)) {
        return true;
    }
    return false;
}

